### ISSUE TITLE
Error: Table extension not working

### ISSUE THREAD

**Issue by dipskakadiya** [showdownjs/table-extension#5]
"DEPRECATION WARNING: table is an old extension that uses a deprecated loading method.Please inform the developer that the extension should be updated!"
# I/p : 

var converter = new showdown.Converter({extensions: ['table']}),
    input = '| Col 1   | Col 2                                              |' +
            '|======== |====================================================|' +
            '|**bold** | ![Valid XHTML](http://w3.org/Icons/valid-xhtml10) |' +
            '| Plain   | Value                                              |';
    html = converter.makeHtml(input);
    console.log(html);
#0/p : 

undefined
"DEPRECATION WARNING: table is an old extension that uses a deprecated loading method.Please inform the developer that the extension should be updated!" showdown.js:3:4028
"<p>| Col 1   | Col 2                                              ||======== |====================================================||<strong>bold</strong> | <img src="http://w3.org/Icons/valid-xhtml10" alt="Valid XHTML" /> || Plain   | Value

**Comment by pdeschen** [comment]
What is your point with this?

**Comment by PatelUtkarsh** [comment]
![js warning](https://cloud.githubusercontent.com/assets/5015489/8352449/daa3ee34-1b52-11e5-92a9-0b6ca360a82b.png)

**Comment by pdeschen** [comment]
Ok wasn't clear at first sight. @tivie did release a new extension loading mechanism and some work might be pending into other extensions such as this one. Hold tight.

**Comment by tivie** [comment]
@PatelUtkarsh This is just a WARNING, it was I who put it there (lol). Old extensions work, the legacy support is present. The extension will be updated once we finalize the last bits of the extension mechanism.

@pdeschen The extension loading mechanism changed, but old extensions work. I had to rewrite it because extensions were not working together in Node.js. I will open a proper issue explaining the situation when I have the time.

**Comment by PatelUtkarsh** [comment]
Okay waiting for update thank you @tivie :+1:
